CREATE TABLE grupo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    ativo     BOOLEAN,
    admin     BOOLEAN,
    CONSTRAINT pk_grupo PRIMARY KEY (id)
);

CREATE TABLE grupo_funcionalidade
(
    grupo_id       BIGINT NOT NULL,
    funcionalidade VARCHAR(255)
);